version: "3.6"

services:
  app:
    image: appliedblockchain/launchpad-ssr-app
    build:
      context: .
      args:
        - PORT=80
        - DB_HOST=postgres
    ports:
      - 80:80
    depends_on:
      - postgres
    environment:
      - CONTRACT_ADDRESSES={"HelloWorld":"0x2Bd63177f61D0Dc67534d48406c1849005dfE04B"}
      - DB_HOST=postgres
      - ETHEREUM_JSONRPC_ENDPOINT=http://parity:8545
    networks:
      - main
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=ssr
    image: postgres
    restart: unless-stopped
    networks:
      - main
  parity:
    image: appliedblockchain/parity-solo-instant:latest
    restart: always
    volumes:
      - parity:/solo/chains
    ports:
      - 8545:8545
      - 8546:8546
    networks:
      - main
  logspout:
    image: gliderlabs/logspout
    deploy:
      mode: global
    environment:
      - SYSLOG_HOST=logs.papertrailapp.com:34888
    command: syslog+tls://$$SYSLOG_HOST
    volumes:
      - type: bind
        target: /var/run/docker.sock
        source: /var/run/docker.sock

volumes:
  parity:
  database:
networks:
  main: