version: "3.6"

services:
  app:
    image: appliedblockchain/launchpad-ssr-app
    build:
      context: .
      args:
        - PORT=80
        - DB_HOST=postgres
    ports:
      - 80:80
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=ssr
    image: postgres
    restart: unless-stopped
