version: '3.6'

services:
  database:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=ssr
    image: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - main
  parity:
    image: appliedblockchain/parity-solo-instant:latest
    restart: always
    volumes:
      - parity:/solo/chains
    ports:
      - 8545:8545
      - 8546:8546
    networks:
      - main

volumes:
  parity:
  database:
networks:
  main: