version: '3.6'

services:
  database:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=ssr
    image: postgres
    ports:
      - 5432:5432
    restart: unless-stopped
